Added README.md
Omega-Numworks/Omega-Robot pull request #2
Opened 2020-11-15 21:08 UTC by hectornuss

2020-11-15 21:41 UTC, quentinguidee requested changes

2020-11-15 21:41 UTC, quentinguidee commented on README.md
> +Yes, you can contribute to this repo by creating a pull-request
I don't think this part is necessary 🤔

2020-11-15 21:41 UTC, quentinguidee commented on README.md
> + - [ ]  Old comands like !hug
The user doesn't know anything this "famous old command hug"

2020-11-15 21:41 UTC, quentinguidee commented on README.md
> + - [ ]  And more comming later!
```suggestion
 - [ ] Linking Epsilon  and Omega issues and pull request when they are called with #1e for Epsilon and #1 for Omega
 - [ ] Old comands like !hug
 - [ ] And more comming later! 
```

2020-11-15 21:41 UTC, quentinguidee commented on README.md
> +--*In developpement*--
You could put a shield.io tag instead :)

2020-11-15 21:41 UTC, quentinguidee commented on README.md
> +This is a bot for our discord, it will include many features.
According to me, "it will include many features" is not a very useful information in a README.

2020-11-16 21:02 UTC, Shadow15510 commented
You can take ideas were raised in the discussion.
Screenshot :
![CdC Omega-Robot](https://user-images.githubusercontent.com/67319895/99307825-55b31e80-2857-11eb-830d-dd5a2691e1c9.png)

2020-11-16 22:24 UTC, quentinguidee requested changes

2020-11-16 22:24 UTC, quentinguidee commented on README.md
> +
```suggestion
```

2020-11-16 22:24 UTC, quentinguidee commented on README.md
> +- [ ] Differentiate perfectly and cleanly the 2 servers
Nothing to change, but I like this part!

2020-11-16 22:24 UTC, quentinguidee commented on README.md
> +- [ ] Old comands like !hug (send a random hug gif)
```suggestion
- [ ] Commands like `!hug` (send a random hug gif)
```

I would rather not referencing the old bot in this new one.

2020-11-16 22:24 UTC, quentinguidee commented on README.md
> +  <a href="https://github.com/Omega-Numworks/Omega-Robot"> <img alt ="Status" src="https://img.shields.io/badge/Status-Under%20developpement-yellow?style=for-the-badge&logo=appveyor"> </a>
```suggestion
  <a href="https://github.com/Omega-Numworks/Omega-Robot"> <img alt ="Status" src="https://img.shields.io/badge/Status-Under%20developpement-yellow?style=for-the-badge"> </a>
```

I think it's better without this icon (?)

2020-11-16 22:24 UTC, quentinguidee commented on README.md
> +</p>
Maybe try without the `<br/>` tags?

2020-11-16 22:24 UTC, quentinguidee commented on README.md
> +This is a bot for our two discord servers
```suggestion
This is a bot for our two discord servers.
```

2020-11-17 09:25 UTC, quentinguidee requested changes

2020-11-17 09:25 UTC, quentinguidee commented on README.md
> +# How can I contribute ?
```suggestion
## How can I contribute ?
```

2020-11-17 09:25 UTC, quentinguidee commented on README.md
> +#  What are the features?
```suggestion
##  What are the features?
```

2020-11-17 09:25 UTC, quentinguidee commented on README.md
> +# What it has to respect
```suggestion
## What it has to respect 
```

2020-11-17 09:25 UTC, quentinguidee commented on README.md
> +
```suggestion
```

2020-11-17 09:27 UTC, quentinguidee requested changes

2020-11-17 09:27 UTC, quentinguidee commented on README.md
> +
```suggestion
```

2020-11-20 09:27 UTC, quentinguidee approved these changes

2020-11-20 09:29 UTC, merged