Hex color code embed
Omega-Numworks/Omega-Robot pull request #23
Opened 2021-07-16 21:02 UTC by Syycorax

### This code is currently **UNTESTED**
Send an embed when a hex color code (#ffffff) is sent

2021-07-16 21:10 UTC, Tim-ats-d requested changes

2021-07-16 21:10 UTC, Tim-ats-d commented on cogs/omega.py
> +            x = requests.get('https://www.thecolorapi.com/id?hex='+ hex_code).json()
You should name variable `x` by a more explicit name (like `req` or `res`)

2021-07-16 21:10 UTC, Tim-ats-d commented on cogs/omega.py
> +            embed = Embed(title='Color #' + title + rgb, color='0x' + hex_code)
Use f-string
```suggestion
            embed = Embed(title=f"Color #{title}{rgb}", color=f"0x{hex_code}")
```

2021-07-16 21:10 UTC, Tim-ats-d commented on cogs/omega.py
> +import requests
Import need sorted by alphabetical order.

2021-07-16 21:14 UTC, Tim-ats-d commented
You need to add a docstring at your method

2021-07-16 21:37 UTC, Tim-ats-d approved these changes

2021-07-19 11:07 UTC, Guiguim255 approved these changes
All good but why adding a blank line in the imports ?

2021-07-19 13:28 UTC, merged